### ISSUE TITLE
프로젝트 기획

### ISSUE THREAD

**Issue by hkoo9329** [leejuhyeok/study-git#3]
## 사용 기술
1. (backend) Spring 4~5 or Spring boot (임시)
2. (DB) Mysql
3. (frontend) react (임시) or javascript, Jquery, ajax, jsp or (임시)vue.js
4. (orm) mybatis or JPA(임시)
5. gradle 4+ or maven 3.2+

## 필요 기능
1. 채팅 채널 만들기
2. 채팅에서 파일 업로드 다운로드 기능
3. 채널에 초대 기능 ( 채널에 있는 사용자만 가능)
4. (시간이 허락한다면) 사용자의 편의 기능을 제공해주는 봇 (채널에서 특정 명령어에 따른 대답 형식)
5. (시간이 허락한다면) 해당 채널 팀에서 to do List 기능

## 생각해봐야 할것
- text 및 업로드 파일 용량 문제
- 로그아웃 이후 특정 채널에 어떻게 다시 연결시킬지
- 로그아웃 이후에 메시지들에 대한 처리 문제

**Comment by hkoo9329** [comment]
**생각나시는 의견을 댓글로 남겨주시면 감사합니다.**

**Comment by jny9708** [comment]
채팅같은 양방향통신은 롱폴링, 웹소켓 이런 것들이 있던데 어떤 방식으로 할건지, 웹소켓으로 할거면 순수 웹소켓을 이용할 것인지 아니면 socketjs, stomp를 이용할 것인지를 정해야할 것 같아요.

로그아웃 이후 특정 채널에 어떻게 다시 연결시킬지를 한번 찾아봤는데요.
먼저 그 특정 채널에 유저가 가입을 할 때 그 가입정보를 데이터베이스에 저장을 시켜놓고, 유저가 로그아웃 후 재로그인하게 된다면 유저가 가입한 채널정보를 데이터베이스에서 가져와서 웹소켓으로 다시 연결 시켜주면 되지 않을까요?

**Comment by hkoo9329** [comment]
로그아웃 후 재연결은 그런 방식을 하면 될거 같네요. 
일단은 저는 stomp에 한표인데 일단은 소켓에 대해서 좀 더 알아보고 해봐야할거 같습니다.
